package com.example.vehiclebreakdownbuddy;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

public class sginupActivity extends AppCompatActivity {

    //Declare variables to store UI elements
    EditText signupName, signupUsername, signupEmail, signupPassword;
    TextView loginRedirectText;
    Button signupButton;
    FirebaseDatabase database;
    DatabaseReference reference;

    @Override
    // This method is called when the activity is created
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sginup);//Set the activity layout

        // Initialize UI elements by finding their respective IDs in the layout

        /*findViewById --> This method is used to locate and retrieve the UI element with the specified ID,
         * e.g.- signup_name, from the XML layout associated with the current activity.
         * --> The R.id.signup_name refers to a unique identifier generated by Android for the EditText element with the
         * ID signup_name in the XML layout. This method returns a reference to the UI element if found, or null if not found.*/

        signupName = findViewById(R.id.signup_name);
        signupEmail = findViewById(R.id.signup_email);
        signupUsername = findViewById(R.id.signup_username);
        signupPassword = findViewById(R.id.signup_password);
        loginRedirectText = findViewById(R.id.loginRedirectText);
        signupButton = findViewById(R.id.signup_button);

        //Set a click listener for the signup

        /* setOnClickListener --> This method is used to define a click event listener for the button. It takes a parameter,
          * which is an instance of the View.OnClickListener interface. This interface defines a single method, onClick,
          * which is called when the button is clicked.

          * new View.OnClickListener() --> This is an anonymous inner class that implements the View.OnClickListener interface. Inside the curly braces {},
          * you define the onClick method's behavior, which will be executed when the button is clicked.*/
        signupButton.setOnClickListener(new View.OnClickListener() {
            @Override
            //This method is executed when SignUp button is clicked
            public void onClick(View view) {

                //Initialize the firebase database and reference
                /* FirebaseDatabase.getInstance(); --> This retrieves an instance of the Firebase Realtime Database, allowing interaction with the Firebase database service.
                * reference = database.getReference("users"); --> This creates a reference to a location within the database.
                *  In this case, it's creating a reference to the "users" node, where user information will be stored.*/
                database = FirebaseDatabase.getInstance();
                reference = database.getReference("users");

                // Get user input values from EditText fields
                /* getText() -->This method retrieves the text content of a UI element, like an EditText, usually for further processing or manipulation.
                *  toString() --> This method converts the retrieved text, which is typically in a character sequence format, into a string format that can be used more flexibly in various contexts.*/
                String name = signupName.getText().toString();
                String email = signupEmail.getText().toString();
                String username = signupUsername.getText().toString();
                String password = signupPassword.getText().toString();

                // Create a Helper object with user information
                Helper helperClass = new Helper(name, email, username, password);

                // Store the user information in the Firebase database under their username
                reference.child(username).setValue(helperClass);

                // Display a toast message to indicate successful signup
                Toast.makeText(sginupActivity.this, "You have signup successfully!", Toast.LENGTH_SHORT).show();

                // Create an intent to navigate to the loginActivity
                /* Intent intent = new...(...); --> This creates an intent, a structure used to communicate between components in Android.
                 * It signifies an intention to transition from the current SignupActivity to the loginActivity class.*/
                Intent intent = new Intent(sginupActivity.this, loginActivity.class);
                startActivity(intent);
            }
        });

        // Set a click listener for the loginRedirectText
        loginRedirectText.setOnClickListener(new View.OnClickListener() {
            @Override
            // This method is executed when the loginRedirectText is clicked
            public void onClick(View view) {

                // Create an intent to navigate to the loginActivity
                Intent intent = new Intent(sginupActivity.this, loginActivity.class);
                startActivity(intent);// Start the loginActivity
            }
        });
    }
}